//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.28 at 03:34:44 ¤U¤È CST 
//


package epcglobal.ale.xsd._1;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import epcglobal.xsd._1.Document;
import org.w3c.dom.Element;


/**
 * 
 *              An ECSpec describes an event cycle and one or more reports that are to
 *              be generated from it. It contains a list of logical readers whose reader
 *              cycles are to be included in the event cycle, a specification of read
 *              cycle timing, a specification of how the boundaries of event cycles are
 *              to be determined, and list of specifications each of which describes a
 *              report to be generated from this event cycle.
 *             
 * 
 * <p>Java class for ECSpec complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ECSpec">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:epcglobal:xsd:1}Document">
 *       &lt;sequence>
 *         &lt;element name="logicalReaders" type="{urn:epcglobal:ale:xsd:1}ECLogicalReaders"/>
 *         &lt;element name="boundarySpec" type="{urn:epcglobal:ale:xsd:1}ECBoundarySpec"/>
 *         &lt;element name="reportSpecs" type="{urn:epcglobal:ale:xsd:1}ECReportSpecs"/>
 *         &lt;element name="extension" type="{urn:epcglobal:ale:xsd:1}ECSpecExtension" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="includeSpecInReports" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ECSpec", propOrder = {
    "logicalReaders",
    "boundarySpec",
    "reportSpecs",
    "extension",
    "any"
})
public class ECSpec
    extends Document
{

    @XmlElement(required = true)
    protected ECLogicalReaders logicalReaders;
    @XmlElement(required = true)
    protected ECBoundarySpec boundarySpec;
    @XmlElement(required = true)
    protected ECReportSpecs reportSpecs;
    protected ECSpecExtension extension;
    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAttribute
    protected Boolean includeSpecInReports;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the logicalReaders property.
     * 
     * @return
     *     possible object is
     *     {@link ECLogicalReaders }
     *     
     */
    public ECLogicalReaders getLogicalReaders() {
        return logicalReaders;
    }

    /**
     * Sets the value of the logicalReaders property.
     * 
     * @param value
     *     allowed object is
     *     {@link ECLogicalReaders }
     *     
     */
    public void setLogicalReaders(ECLogicalReaders value) {
        this.logicalReaders = value;
    }

    /**
     * Gets the value of the boundarySpec property.
     * 
     * @return
     *     possible object is
     *     {@link ECBoundarySpec }
     *     
     */
    public ECBoundarySpec getBoundarySpec() {
        return boundarySpec;
    }

    /**
     * Sets the value of the boundarySpec property.
     * 
     * @param value
     *     allowed object is
     *     {@link ECBoundarySpec }
     *     
     */
    public void setBoundarySpec(ECBoundarySpec value) {
        this.boundarySpec = value;
    }

    /**
     * Gets the value of the reportSpecs property.
     * 
     * @return
     *     possible object is
     *     {@link ECReportSpecs }
     *     
     */
    public ECReportSpecs getReportSpecs() {
        return reportSpecs;
    }

    /**
     * Sets the value of the reportSpecs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ECReportSpecs }
     *     
     */
    public void setReportSpecs(ECReportSpecs value) {
        this.reportSpecs = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link ECSpecExtension }
     *     
     */
    public ECSpecExtension getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ECSpecExtension }
     *     
     */
    public void setExtension(ECSpecExtension value) {
        this.extension = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets the value of the includeSpecInReports property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIncludeSpecInReports() {
        if (includeSpecInReports == null) {
            return false;
        } else {
            return includeSpecInReports;
        }
    }

    /**
     * Sets the value of the includeSpecInReports property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeSpecInReports(Boolean value) {
        this.includeSpecInReports = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
